basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = "basic_app"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('user_login/', views.user_login, name="user_login")
]

registration/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("basic_app/", include("basic_app.urls")),
    path("logout/", views.user_logout, name="logout"),
    path("special/", views.special, name="special")
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfoModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    protfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __self__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfoModel


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "email", "password")
 

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfoModel
        fields = ("protfolio_site", "profile_pic")

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required # called itself
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user.form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, "basic_app/registration.html", {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html', {})
    pass

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Registration</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                </ul>
                <span class="navbar-text">
                    {% if user.is_authenticated %}
                    <a href="#">{{user.username}}</a>
                    <a href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a href="{% url 'basic_app:register' %}">Register</a>
                    <a href="{% url 'basic_app:user_login' %}">Login</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"></script>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

templates/basic_app/login.html
{% extends "basic_app/base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="POST"> {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for resitering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="POST"> {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>

{% endblock %}